
from enum import Enum


class LogSeverity(str, Enum):
    UNKNOWN = "UNKNOWN"
    unknown = "UNKNOWN"
    TRACE = "TRACE"
    trace = "TRACE"
    DEBUG = "DEBUG"
    debug = "DEBUG"
    INFO = "INFO"
    info = "INFO"
    WARNING = "WARNING"
    warning = "WARNING"
    ERROR = "ERROR"
    error = "ERROR"
    CRITICAL = "CRITICAL"
    critical = "CRITICAL"
    NOTICE = "NOTICE"
    notice = "NOTICE"
    FATAL = "FATAL"
    fatal = "FATAL"


class LogSourceType(str, Enum):
    UNKNOWN = "UNKNOWN"
    unknown = "UNKNOWN"
    FILE = "FILE"
    file = "FILE"
    SYSLOG = "SYSLOG"
    syslog = "SYSLOG"
    HTTP = "HTTP"
    http = "HTTP"
    DATABASE = "DATABASE"
    database = "DATABASE"
    WINDOWS_EVENT = "WINDOWS_EVENT"
    windows_event = "WINDOWS_EVENT"
    APPLICATION = "APPLICATION"
    application = "APPLICATION"
    IIS = "IIS"
    iis = "IIS"
    REDIS = "REDIS"
    redis = "REDIS"
    JSON = "JSON"
    json = "JSON"
    XML = "XML"
    xml = "XML"
    CSV = "CSV"
    csv = "CSV"
    NGINX = "NGINX"
    nginx = "NGINX"
    APACHE = "APACHE"
    apache = "APACHE"
    LINUX_SYSLOG = "LINUX_SYSLOG"
    linux_syslog = "LINUX_SYSLOG"
    KUBERNETES = "KUBERNETES"
    kubernetes = "KUBERNETES"
    OPENSHIFT = "OPENSHIFT"
    openshift = "OPENSHIFT"
    JENKINS = "JENKINS"
    jenkins = "JENKINS"


class ParseStatus(str, Enum):
    SUCCESS = "SUCCESS"
    success = "SUCCESS"
    FAILURE = "FAILURE"
    failed = "FAILURE"
    PARTIAL = "PARTIAL"
    partial = "PARTIAL"

class ErrorType(str, Enum):
    UNKNOWN = "UNKNOWN"
    unknown = "UNKNOWN"
    PARSING = "PARSING"
    parsing = "PARSING"
    VALIDATION = "VALIDATION"
    validation = "VALIDATION"
    INGESTION = "INGESTION"
    ingestion = "INGESTION"
    UNKNOWN_FORMAT = "UNKNOWN_FORMAT"
    unknown_format = "UNKNOWN_FORMAT"
    EMPTY_INPUT = "EMPTY_INPUT"
    empty_input = "EMPTY_INPUT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    internal_error = "INTERNAL_ERROR"
    DETECTION_FAILED = "DETECTION_FAILED"
    detection_failed = "DETECTION_FAILED"
    PARSE_FAILED = "PARSE_FAILED"
    parse_failed = "PARSE_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    validation_failed = "VALIDATION_FAILED"
