
"""Custom exceptions for the Log Parser Engine."""

from .analysis import (
    AnalysisComparisonError,
    AnalysisConcurrencyLimitError,
    AnalysisConfigurationError,
    AnalysisError,
    AnalysisEventLimitError,
    AnalysisFieldResolutionError,
    AnalysisGroupLimitError,
    AnalysisInsufficientDataError,
    AnalysisNumericValueError,
    AnalysisRequestError,
    AnalysisSampleLimitError,
    AnalysisTimelineLimitError,
)
from .batch import (
    BatchOrchestrationError,
    BatchProcessingError,
    InvalidBatchItemError,
)
from .detection import (
    DetectionError,
    DetectorInternalError,
    DuplicateParserError,
    NoParserFoundError,
    UnsupportedLogFormatError,
)
from .iis import (
    IisFieldMappingError,
    IisHeaderError,
    IisParserError,
    IisTokenizationError,
)
from .ingestion import (
    ArchiveBombError,
    ArchiveEntrySelectionError,
    ArchiveEntryTooLargeError,
    ArchiveError,
    ArchiveNotAllowedError,
    BinaryContentError,
    EmptyContentError,
    EncodingDetectionError,
    EncryptedArchiveError,
    IngestionError,
    InputNotFoundError,
    InputPermissionError,
    InputSourceError,
    InputTooLargeError,
    NestedArchiveError,
    SourceReaderError,
    SymlinkNotAllowedError,
    TextDecodingError,
)
from .json_parser import (
    JsonDecodingError,
    JsonFieldPathError,
    JsonMappingError,
    JsonParseError,
    JsonParserError,
    JsonProfileError,
    JsonStructureError,
)
from .normalization import NormalizationError
from .parser_registry import (
    ParserAlreadyRegisteredError,
    ParserConfigurationError,
    ParserDiscoveryError,
    ParserNotFoundError,
    ParserRegistrationError,
    ParserRegistrationMismatchError,
)
from .pipeline import PipelineConfigurationError, PipelineError, PipelineStageError
from .plugin import (
    InvalidPluginError,
    PluginDiscoveryError,
    PluginError,
    PluginFactoryError,
    PluginLoadError,
    PluginStartupError,
    PluginValidationError,
)
from .redis import (
    RedisClassificationError,
    RedisMappingError,
    RedisParserError,
    RedisTimestampError,
    RedisTokenizationError,
)
from .storage import (
    BatchWriteError,
    DuplicateEventError,
    EventAggregationError,
    EventFilterError,
    EventIdCollisionError,
    EventPaginationError,
    EventQueryError,
    EventSnapshotError,
    EventSortError,
    EventStoreCapacityError,
    EventStoreConfigurationError,
    EventStoreError,
    EventTooLargeForStoreError,
    InvalidEventError,
    InvalidEventIdError,
)
from .syslog import (
    SyslogMappingError,
    SyslogParserError,
    SyslogStructureError,
    SyslogTimestampError,
    SyslogTokenizationError,
)
from .windows_event import (
    WindowsEventMappingError,
    WindowsEventParserError,
    WindowsEventStructureError,
    WindowsEventXmlError,
)

__all__ = [
    "AnalysisComparisonError",
    "AnalysisConcurrencyLimitError",
    "AnalysisConfigurationError",
    "AnalysisError",
    "AnalysisEventLimitError",
    "AnalysisFieldResolutionError",
    "AnalysisGroupLimitError",
    "AnalysisInsufficientDataError",
    "AnalysisNumericValueError",
    "AnalysisRequestError",
    "AnalysisSampleLimitError",
    "AnalysisTimelineLimitError",
    # Batch
    "BatchOrchestrationError",
    "BatchProcessingError",
    "InvalidBatchItemError",
    # Detection
    "DetectionError",
    "DetectorInternalError",
    "DuplicateParserError",
    "NoParserFoundError",
    "UnsupportedLogFormatError",
    # Ingestion
    "IngestionError",
    "InputSourceError",
    "InputNotFoundError",
    "InputPermissionError",
    "InputTooLargeError",
    "SymlinkNotAllowedError",
    "BinaryContentError",
    "SourceReaderError",
    "ArchiveError",
    "ArchiveNotAllowedError",
    "ArchiveEntrySelectionError",
    "ArchiveEntryTooLargeError",
    "ArchiveBombError",
    "EncryptedArchiveError",
    "NestedArchiveError",
    "EmptyContentError",
    "EncodingDetectionError",
    "TextDecodingError",
    # JSON
    "JsonParserError",
    "JsonDecodingError",
    "JsonStructureError",
    "JsonFieldPathError",
    "JsonParseError",
    "JsonMappingError",
    "JsonProfileError",
    # Normalization
    "NormalizationError",
    # Parser Registry
    "ParserAlreadyRegisteredError",
    "ParserNotFoundError",
    "ParserRegistrationError",
    "ParserDiscoveryError",
    "ParserConfigurationError",
    "ParserRegistrationMismatchError",
    # Pipeline
    "PipelineError",
    "PipelineConfigurationError",
    "PipelineStageError",
    # Plugin
    "PluginError",
    "PluginDiscoveryError",
    "PluginLoadError",
    "PluginFactoryError",
    "PluginStartupError",
    "InvalidPluginError",
    "PluginValidationError",
    # Storage
    "BatchWriteError",
    "EventStoreError",
    "EventStoreConfigurationError",
    "InvalidEventError",
    "InvalidEventIdError",
    "DuplicateEventError",
    "EventIdCollisionError",
    "EventStoreCapacityError",
    "EventTooLargeForStoreError",
    "EventQueryError",
    "EventFilterError",
    "EventSortError",
    "EventPaginationError",
    "EventAggregationError",
    "EventSnapshotError",
    # IIS
    "IisParserError",
    "IisHeaderError",
    "IisTokenizationError",
    "IisFieldMappingError",
    # Redis
    "RedisParserError",
    "RedisTokenizationError",
    "RedisTimestampError",
    "RedisClassificationError",
    "RedisMappingError",
    # Syslog
    "SyslogParserError",
    "SyslogTokenizationError",
    "SyslogTimestampError",
    "SyslogStructureError",
    "SyslogMappingError",
    # Windows Event
    "WindowsEventParserError",
    "WindowsEventXmlError",
    "WindowsEventStructureError",
    "WindowsEventMappingError",
]
