"""Exceptions for detection, parser selection, and plugin loading."""

from .batch import (
    BatchConfigurationError,
    BatchConsecutiveErrorLimitExceeded,
    BatchDetectionError,
    BatchErrorLimitExceeded,
    BatchErrorRateExceeded,
    BatchMixedFormatError,
    BatchParseError,
    BatchProgressCallbackError,
    BatchRecordTooLargeError,
    BatchSourceError,
    BatchStateError,
    BatchUnsupportedRecordModeError,
)
from .detection import DetectionError, DuplicateParserError
from .iis import (
    IisFieldMappingError,
    IisHeaderError,
    IisParserError,
    IisTokenizationError,
)
from .ingestion import (
    ArchiveBombError,
    ArchiveEntrySelectionError,
    ArchiveEntryTooLargeError,
    ArchiveError,
    ArchiveNotAllowedError,
    BinaryContentError,
    EmptyContentError,
    EncodingDetectionError,
    EncryptedArchiveError,
    IngestionError,
    InputNotFoundError,
    InputPermissionError,
    InputSourceError,
    InputTooLargeError,
    NestedArchiveError,
    SymlinkNotAllowedError,
    TextDecodingError,
)
from .json_parser import (
    JsonDecodingError,
    JsonFieldPathError,
    JsonMappingError,
    JsonParserError,
    JsonProfileError,
    JsonStructureError,
)
from .normalization import NormalizationError
from .parser_registry import (
    ParserAlreadyRegisteredError,
    ParserNotFoundError,
    ParserRegistrationMismatchError,
    ParserRegistryError,
)
from .pipeline import PipelineConfigurationError, PipelineError, PipelineStageError
from .plugin import (
    InvalidPluginError,
    PluginDiscoveryError,
    PluginError,
    PluginFactoryError,
    PluginLoadError,
)
from .redis import (
    RedisClassificationError,
    RedisMappingError,
    RedisParserError,
    RedisTimestampError,
    RedisTokenizationError,
)
from .syslog import (
    SyslogMappingError,
    SyslogParserError,
    SyslogStructureError,
    SyslogTimestampError,
    SyslogTokenizationError,
)
from .windows_event import (
    WindowsEventMappingError,
    WindowsEventParserError,
    WindowsEventStructureError,
    WindowsEventXmlError,
)

__all__ = [
    "DetectionError",
    "DuplicateParserError",
    "BatchConfigurationError",
    "BatchConsecutiveErrorLimitExceeded",
    "BatchDetectionError",
    "BatchErrorLimitExceeded",
    "BatchErrorRateExceeded",
    "BatchMixedFormatError",
    "BatchParseError",
    "BatchProgressCallbackError",
    "BatchRecordTooLargeError",
    "BatchSourceError",
    "BatchStateError",
    "BatchUnsupportedRecordModeError",
    "ArchiveBombError",
    "ArchiveEntrySelectionError",
    "ArchiveEntryTooLargeError",
    "ArchiveError",
    "ArchiveNotAllowedError",
    "BinaryContentError",
    "InvalidPluginError",
    "IisFieldMappingError",
    "IisHeaderError",
    "IisParserError",
    "IisTokenizationError",
    "EmptyContentError",
    "EncryptedArchiveError",
    "EncodingDetectionError",
    "JsonDecodingError",
    "JsonFieldPathError",
    "JsonMappingError",
    "JsonParserError",
    "JsonProfileError",
    "JsonStructureError",
    "NormalizationError",
    "IngestionError",
    "InputNotFoundError",
    "InputPermissionError",
    "InputSourceError",
    "InputTooLargeError",
    "ParserAlreadyRegisteredError",
    "ParserNotFoundError",
    "ParserRegistrationMismatchError",
    "ParserRegistryError",
    "PipelineConfigurationError",
    "PipelineError",
    "PipelineStageError",
    "PluginDiscoveryError",
    "PluginError",
    "PluginFactoryError",
    "PluginLoadError",
    "NestedArchiveError",
    "RedisClassificationError",
    "RedisMappingError",
    "RedisParserError",
    "RedisTimestampError",
    "RedisTokenizationError",
    "SyslogMappingError",
    "SyslogParserError",
    "SyslogStructureError",
    "SyslogTimestampError",
    "SyslogTokenizationError",
    "WindowsEventMappingError",
    "WindowsEventParserError",
    "WindowsEventStructureError",
    "WindowsEventXmlError",
    "SymlinkNotAllowedError",
    "TextDecodingError",
]
